# Use the official MySQL image
FROM mysql:latest

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=admin1234

# Set the database name, user, and password
ENV MYSQL_DATABASE=MarketPlace
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin1234

# Expose the MySQL port
EXPOSE 3306
